
print("\n")
print('________________________________________')
print("|                                      |")
print('|        ¡Bienvenido a LUBUNTU!        |')
print("|                                      |")
print("|  Esta: \" \" es una forma de imprimir  |")
print('|        Esta: \' \' es otra forma       |')
print("|                                      |")
print("|______________________________________|")
print("\n")
